FROM python:3.10

WORKDIR /app

COPY requirements/* requirements/

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements/development.txt

COPY . .

ENV APP_RELEASE ${APP_RELEASE}
ENV APP_ENVIRONMENT ${APP_ENVIRONMENT}

ENV FLASK_DEBUG ${FLASK_DEBUG}
ENV FLASK_RUN_PORT ${FLASK_RUN_PORT}
ENV FLASK_RUN_HOST ${FLASK_RUN_HOST}
ENV FLASK_DEBUGGER ${FLASK_DEBUGGER}
ENV FLASK_DEBUGGER_PORT ${FLASK_DEBUGGER_PORT}

ENV MONGODB_URL ${MONGODB_URL}
ENV MONGODB_NAME ${MONGODB_NAME}

ENV DEBUG_METRICS true
ENV SENTRY_DSN ${SENTRY_DSN}

ENV X_API ${X_API}
ENV X_API_KEY ${X_API_KEY}

CMD gunicorn -c gunicorn.py main:app
