version: "3.9"

services:
  mongodb:
    image: mongo:5.0.2
    container_name: cart-api_mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  app: &app
    build:
      context: .
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_DEBUG_PORT: ${FLASK_DEBUG_PORT}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_URL: ${MONGODB_URL}
      X_API: ${X_API}
      X_API_KEY: ${X_API_KEY}
    depends_on:
      - mongodb

  cart_api:
    <<: *app
    container_name: cart-api
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
      - ${FLASK_DEBUG_PORT}:${FLASK_DEBUG_PORT}
    volumes:
      - ./:/app

  runner:
    <<: *app
    env_file:
      - .env
    command: /bin/bash

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: cart-api_prometheus
    command:
      - --web.config.file=/prometheus/web.yml
    volumes:
      - ./.monitoring/prometheus/:/prometheus/
    ports:
      - 3000:9090

  grafana:
    image: grafana/grafana:9.3.6
    container_name: cart-api_grafana
    environment:
      PROMETHEUS_USER: ${PROMETHEUS_USER}
      PROMETHEUS_PASSWORD: ${PROMETHEUS_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - ./.monitoring/grafana/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./.monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    ports:
      - 3001:3000

volumes:
  mongodb:
