FROM python:3.10

WORKDIR /app

COPY requirements/* requirements/

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements/development.txt

COPY . .

ENV FLASK_DEBUG ${FLASK_DEBUG}
ENV FLASK_RUN_PORT ${FLASK_RUN_PORT}
ENV FLASK_RUN_HOST ${FLASK_RUN_HOST}
ENV FLASK_DEBUGGER ${FLASK_DEBUGGER}
ENV FLASK_DEBUGGER_PORT ${FLASK_DEBUGGER_PORT}

ENV MONGODB_NAME ${MONGODB_NAME}
ENV MONGODB_URL ${MONGODB_URL}

ENV DEBUG_METRICS true

ENV X_API ${X_API}
ENV X_API_KEY ${X_API_KEY}

CMD flask run
