version: "3.9"

services:
  mongo:
    image: mongo:5.0.2
    container_name: cart_mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${MONGODB_PORT}

  app: &app
    build:
      context: .
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUGGER: ${FLASK_DEBUGGER}
      FLASK_PORT: ${FLASK_PORT}
      FLASK_DEBUG_PORT: ${FLASK_DEBUG_PORT}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_URL: ${MONGODB_URL}
      X_API: ${X_API}
      X_API_KEY: ${X_API_KEY}
    depends_on:
      - mongo

  cart_api:
    <<: *app
    container_name: cart_api
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
      - ${FLASK_DEBUG_PORT}:${FLASK_DEBUG_PORT}
    volumes:
      - ./:/app

  runner:
    <<: *app
    env_file:
      - .env
    command: /bin/bash

volumes:
  mongo:
