apiVersion: apps/v1
kind: Deployment
metadata:
  name: loja-integrada.cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: docker.io/rempeloliveira/public:cart-api
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-hub-credentials
