apiVersion: v1
kind: Service
metadata:
  name: li-cart-api
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cart-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: li-cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: docker.io/rempeloliveira/public:cart-api
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-hub-credentials
