apiVersion: v1
kind: Service
metadata:
  name: li-cart-api
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cart-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: li-cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: rempeloliveira/public:cart-api.v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd-apps
data:
  exec.enabled: "true"
  exec.shells: "bash,sh,powershell,cmd"
