apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
  namespace: staging-apps
spec:
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
  selector:
    app: cart-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-deployment
  namespace: staging-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: rempeloliveira/public:cart-api.v1
          ports:
            - containerPort: 80
