apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
  namespace: staging-apps
spec:
  selector:
    app: cart-api
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-deployment
  namespace: staging-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: rempeloliveira/public:cart-api.v2
          ports:
            - containerPort: 80
          env:
            - name: FLASK_ENV
              valueFrom:
                secretKeyRef:
                  name: cart-api-secret
                  key: FLASK_ENV
            - name: FLASK_DEBUGGER
              valueFrom:
                secretKeyRef:
                  name: cart-api-secrets
                  key: FLASK_DEBUGGER
            - name: FLASK_PORT
              valueFrom:
                secretKeyRef:
                  name: cart-api-secrets
                  key: FLASK_PORT
            - name: FLASK_DEBUG_PORT
              valueFrom:
                secretKeyRef:
                  name: cart-api-secrets
                  key: FLASK_DEBUG_PORT
            - name: MONGODB_NAME
              valueFrom:
                secretKeyRef:
                  name: cart-api-secrets
                  key: MONGODB_NAME
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: cart-api-secrets
                  key: MONGODB_URL
            - name: X_API
              valueFrom:
                secretKeyRef:
                  name: cart-api-secrets
                  key: X_API
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cart-api-secrets
                  key: X_API_KEY
