kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: production-apps
stringData:
    APP_RELEASE: ENC[AES256_GCM,data:ySVLc1o=,iv:pPtLbSJ8Tj9W3h7i2wrBOMqdjwezNo8jMSGDWshX+A4=,tag:g7nxFOy2OiBYwSaVQbKzMQ==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:Jc7o4nWmToNgUg==,iv:lkq5JHANStU6O8Awfp9j3CMeiB5BsrLey1zZIaMj5iY=,tag:K8XStMmyugGt4hTdm3tccw==,type:str]
    FLASK_DEBUG: ENC[AES256_GCM,data:eEv1Fzw=,iv:5c+7bFiiPb6/WQ8poeWs6aAK/wMtXhre4Zj0XV3eB9o=,tag:t9IXsJc1r9qJaejZIksIjw==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:s9g=,iv:ybXC4Knh8dcjsHUlJ4p9GsLAyKY9koINAqbAmouycO8=,tag:cCM6srXdx9jQThH4CAKamg==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:X2cKCXSJSA==,iv:GHi3iyFPQG3eWCeDssAWwa+0OIBgDfRQowTkTEVZXcw=,tag:hHjUsmfeK9XBTe6APIKJUQ==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:48XrBJU=,iv:vvTe4X0ZzV/Bc9HOKChJZqMgSHi7cGm7b1eScKjGgBA=,tag:98+BqFsaATDt7LNXcfKWEg==,type:str]
    FLASK_DEBUGGER_PORT: ""
    MONGODB_URL: ENC[AES256_GCM,data:PxeeVD9wkiFK1P9yMQnhU5YawtV2h5i6ku7DkUSWtShp8FTSDx7rCE8a0oE+JYOebJeNJA==,iv:KAT7cL0wQXaFO79FalRHMGA9dAx0V5ukW0y1Gideis4=,tag:PuIVrTqjC5RwvNmbociXow==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:IX1IbK+fHZk=,iv:ep5cla45AGIYUMBrSSGQaEX1bmyx2nxKqnr4cIJgDwc=,tag:+4UpdGI3X0ipqZUEViA6bA==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:9q/HvA==,iv:jPDTaknxRWqaLOm3SZSgweJu1uNElpRsI6PGE1F3m6k=,tag:qlDyZKPQDczAdUuxLo2hWw==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:NY4cvw==,iv:5ln73RQaB8sT9GWcZPE6k8joicl+TWCx2phlvatXo+Q=,tag:d2n/3RxwLeSH1LbDqSWtUQ==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:1DylS+9+2xd9oWAmPCwP8laBh9JqvouP0zbrg7nNyhs7Tm0+jq/M50AqBqROF/rGDeNWFoZreJJjIY5Db39rLj00Gw==,iv:WkVc2zxiIzUKTZ70zNAeAHAH5FJHIHhLcHTzemlksQA=,tag:/OJoSpRIDvRQunFkRNzoCg==,type:str]
    X_API: ENC[AES256_GCM,data:3aYv4odIzXZdCjVpfC5KIfJ8r8Ld1Eqs8ES8L8aj34c+P7Htap6+sf2NssgvnE+mGLeix2WG8AQEiQ==,iv:qe1nkd9xMkQdIDZEh7JMLksZE5x9f5hahqPDoFwQEyA=,tag:cKZJsZW24Wbum6IEq+YevA==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:11SlpgnEVGilYTnIndi1pdtRQwFjT3Rref7qsbO0y9xGBPbhENG3SdygZWUjAqMf88SHTP25FVc4beCCITwAwQ==,iv:RGK89+0tYsVNYVBiyCi2RcZf9N34fK/R/RVBdpQ1f3c=,tag:Pww5QxP0KES8ktZ0at1wAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOUtvVkRmZUs0ZnZmaUJW
            WnlsVzhrM1FDbGNETXBOUXdmNDJpSmFLTm5zCm45U0RYYUtJbmV6c3p3QUZEdnVI
            UWdSZTg3M1lHRTdyaFF0cFFVdnhnMFEKLS0tIHhGV2gxaS8zUHFUQVFxeGJnNVFT
            WEJnNzI4MVloRzRJRDlsYUxleFVDZFUKzkEHr0/DKoWGVp1pLLsQzaf3EvQLD0Mi
            xxW7bOOHmSGr7+XsDds7LSh4qteAqSMu8kUgWWZSUOKk9xb81K5BlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T17:17:12Z"
    mac: ENC[AES256_GCM,data:SZz2lQ3hEbM8fC4rm+kbVgUwKIN6wrQVpADzXwu8UCZcFDs6jiWobM2+X5E2f0sEr33MFEuZzp8DAs5lIjW4bwCnKgdzI/vV1uKCIBBQz+BwWCafoWRmeAQuFq/YOwNMCxLoJ/H1RhWuMd2g4OvMRaoMoBpZesJ97lNahIugQjQ=,iv:0gkMJ6+8zYzhR7UBaqWQ97YSDIM7HlmP2u+V9RXEyP8=,tag:qsuLPF78jyiorUI2KdZcZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
