kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:/u+/gA==,iv:tMttxBfCMrGMCAJ/uTO7c9jKLCfXr491Ar420zBE/1I=,tag:f7SDx6u501JL18Hr44+vbA==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:x6s=,iv:DOiY5Obnq4E2ciuS5vvrzrkw7OSejMy5UwWpuLjwUg8=,tag:ZMfm7vJla55UAxuEGeuWfw==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:YT+D96UlVw==,iv:meC8cqZVJWdAt1N+mCRF7I3Hh55LOMEZdPeZPPRv9FQ=,tag:P3Er8ZWFlq2Y+NA+F0PrBg==,type:str]
    FLASK_DEBUG_PORT: ENC[AES256_GCM,data:pbUy4w==,iv:qA3RkvRx6EouIhLLHvEFs9QQzAH+/ViGo5PT83BTgPE=,tag:qa+7qqiDSI+1wvvpBlFXoQ==,type:str]
    MONGODB_URL: ENC[AES256_GCM,data:nY2i5R9bzz8GldJ2/EvSUQrOU+Ca+5tHu/sIutkeYhqpk2UGQh8psFPSOMFXMgLHB8Phhg==,iv:StKNFh0C5/7wtJkzW5Ivy33dZ19lu8o4Rkz+H+DklO0=,tag:fSdEezS0wd8SEPFK9NPUDg==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:ivEBT0nJIL4=,iv:JUrV1RISGwxF6yGIfesOSGy0l8kfT1EqYDNRSp6fGQY=,tag:P02iqct+8IMEBbWwQ4CMog==,type:str]
    X_API: ENC[AES256_GCM,data:D/BrDzbV5MP76fwyInQzIzZsNpZCgZSDG0H8whiU+41SkNTQH15PJbmZDpzEs0C1iyJZ8gx+iFYYBQ==,iv:XjskdzfBPkDAJcppHwlNR2hB31y8FktgOh1MLjfRbEU=,tag:L1IPB9yz+YmPTYzhll30Og==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:f7cKtj1BNgoUbP7OUGGXO/2jgtgAvvNlb9naVLWUoFK5b/a2MyNLpjKyXHL3R/v7v1oOHESj08O5Tmpqs4UEYw==,iv:rp+pKZVJawe6wF3QP0yozNrjQdHEinBCcC2xxrlMEac=,tag:AgwCP5b1smKeckpdRA3+VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-02T21:22:48Z"
    mac: ENC[AES256_GCM,data:Ol5P7uyeoUHSuHtEJwEt7DBLESX9fJqueoCjDoYZmf1zgHe/YcirZrtM5lgxJp2BMINOphZKm4RIuhQSF0laJT+YQk74yI+dD9z72H1tsvjNi0axO74pTeGHkhN4uX6UGtlYZO/YNRcIN+1nhdo7kuQjfLNeY6oKXJ+j41mRLPM=,iv:PD77NXjpqzkgNkqUxvasBYvb86BaD7NibZaJx9VWPWU=,tag:rdxCdvxXTa+S9hYJQjd2OQ==,type:str]
    pgp:
        - created_at: "2023-02-02T21:22:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA72+lVh6XXaqAQ/+IznhFpH9798rEqcDXW1wuFakTsFh26SKwnLyh4/5TrMd
            AhxdbqJ5nlpnmntnBVrdDvfi94EponUPTWbcrejXcXKmr4w9HQWF+73W2vJl+7e7
            h5NJ9qPKFFmt00envU4pC5k62SNY9e+8gT3oJmo/OXI/8KK9fAomNEYDXQ6UdJLO
            0nRFxPf6+78DiY5YddNk1qXy/jVvvn5jdnhCt8/i7km3h2DNVsX6zK481RdkIqMd
            ij3MKkI5qdjwttoNzOsE6XwWwwcrjfZ55u/HIS7MyqmubOgPBJO/oJ2PkFNiBocM
            kRUidtvbaDwrInn9AnlOsKEJ8WiJ2fzL6ABFQ45uipLMHHexgBOFPL+273R3YmUi
            ntf7oq/EcDP2/HmkzEdIvwr0uqlFBGAzyeND4WrglSFmO7tC9lv7Zu2lfWX+YcII
            d+95oE5Jv6TeaRfZAY1dQpZutzOjNXLCJW8yO6eA7ixgBSN9qmjZ+n2AFh5u0ZOG
            xmBy2PU6Bqxp5BvlrGXeQZo6BMnv9Wn6+xeSaqh+yTrJWZxVzasd5NRhk2oFUCfx
            rfiFX9UhO3Wm0j4PS5/ANMReEXvDGrNCIaWJ3E3Ii16mzkJv0ocrXT1FiJ09XZSB
            7A2l8LOc3DS5wGpva7KvTFFrG4X/nmFFyNDYKsQ1FH+sRt1HKXfYQWxzKz2dg3bS
            XgH8a5dgarDQJMBA6v1OPZkFAZyxwKVPVYlzwma87Mgg79bPXH0DPhiVcIboqr6i
            j2+sBwrkvtvCku98ZjJZDAq4oSYVBj+R7Jtk6H9oSR/zKoYotqZcRqYGP/u4I7s=
            =LNwO
            -----END PGP MESSAGE-----
          fp: C0403E232793F0791C00ABA63168101CFA91B3F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
