kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: production-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:EKHd/A==,iv:H0bCzWf7jhzsCpQHRhgg5f0Kkx8AVT0Id2qexxfueNg=,tag:mj906m3DEC83WYLOh6We+g==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:Q3Q=,iv:ABMMlrxvxVqJ8nD/cdgWGmavETI24Y+QgI3ahkIWze8=,tag:0/AT5XtmvPLeADESG/hpfA==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:4lpWtC03NA==,iv:x+5UFAy5D7H1IPXcUXdLlrrElFGJLDeIhI+Vm6M/+2w=,tag:pq7Rq8qeq6OvyiNkkMnITw==,type:str]
    FLASK_DEBUG_PORT: ENC[AES256_GCM,data:sh2Prw==,iv:5/6fKUEnPqcpYdIxQgexPZ56RPg7Gn8qWV3LHh4YpBE=,tag:zT5Ab0EZUJQCOg4fGcjYEQ==,type:str]
    MONGODB_URL: ENC[AES256_GCM,data:nBDIe7fPuS0/lG53lxEln3ZD5DydeFSeJlCEkFCUoC8pDFvC8+oJrwx6ECx8IzXpEzQAcw==,iv:4lFCp+s/6LVydl4lX7xe9YSKknS5NjE9u664uZnt+7c=,tag:5Ysjf2uPya049GFTlAZNgQ==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:TsY50rWAMiY=,iv:asaib2Vj2nPn7hqcroVIWdIeeGsrpMb2WlNEOdfr+wg=,tag:EegEPRuI57CEw5OTDnQPLQ==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:hXZ8/g==,iv:RNznQcAIVKXXByCV+11Z6h54j2gbmci7gilt9MP6GHo=,tag:WwXnDwFHEjcmyXsk8X1d1g==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:WFSWeg==,iv:E+qvAmjXVSQUuQ13M78pO6gGZFc9ET0hISRteqS+oDQ=,tag:2oFHn+0StXJBuhFXRGT0Jw==,type:str]
    X_API: ENC[AES256_GCM,data:iDl+0nKkrOZzmWpLXYvHpS9r1ohEWpRKGOm7mQ+jQ6ZizJKNVbPBJts2NN87UvSDgEyMpbRNj3iW4Q==,iv:MNp70wL6tSRvGFIO8W1SiQ64OQ1BtwpIzfr3/lSXvmw=,tag:wSDAE2IgccDrhfQNZKi7FQ==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:e3QFpiwProTfKiezxMcEBHeN2MATrVHV5Es/Yu5QAyh3umGuDMMF2MlIcHg6kn8pw+Wm9zyPpvKxSZiKtbszcQ==,iv:DliDvmHhnIUayyrNv7PO3+f/H5XEhR5GAEZheskvkwc=,tag:Fl0K56pPwKNxXEAN65dcWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-15T16:23:57Z"
    mac: ENC[AES256_GCM,data:XgkMdfm9gquUekBcKzQ4JimZ4Q18sYjKWzxmx0iD2HEHrGLVoW5EGuuP5yumelDhiveNW5gbYZ7Swnt7rEO4AtZazGwtFr7GhT6fXoWO6qfsf95K+xPrk7EFlPPSCfnEKNDJVTopTCVWnygoZgqPO7ZqlwGio5zaVU+qPH+QBvo=,iv:qR4GyniQyrw8zt0Tza2GJHCG7TN5HCC+FaleiSytbRQ=,tag:wWSOleP6HDwy84pIlUyr6A==,type:str]
    pgp:
        - created_at: "2023-02-15T16:23:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyeXsCGmRZX9AQ//YuR2jPo8Zu7zL/U7B1yyraZMWr6jCmu5lKjr99HhuZ04
            4s7JNbjQA7JwTBMKIHlRBlJ6GCfi4jJccYfoonZsQNdm/HuhJxpD//wyWOGYV9IQ
            XL720lpkmoo2KkDFqNLtzjJWmB2CYGWbGlyW55hImArOp5DkfXnTrO7djFrAxugm
            PQ+Rhde32/r3vU5YZ0RamBafiFgqJm4eeLvOhwRwRjHIUPvaii5mOv4YA1dutw2t
            eoQ6KJohl1ItNKchyEjn+yuJrqg9zpek75CRYM3yGpUeE1TaAZUj8SGyyuE3RSP3
            7LFVXACfCb2D4lJl8RLkTlY17nPWhxQMHu99SnLdlsZq2S2YKLlvReAaK5bgL05n
            wvIAWKakfWZm+FHw3nzNdgZdFrCYx0wvr7ehPmwn7xXFLaUBYvE87kf+4fzlZ7Cx
            kBhBOIjKhZw4xIzknn5f4OW9Oi1pfcRJ8IqnIVjvmf2zR6fTnaN7R7rCPBbD+DJG
            N4woQ0Q9ieh9UDA9vfMkn7TFHBIkMOND/Gq0TMZ0yZTYpxr45eYhqC6z0pUSFfqe
            zx2gcLPvgJKR4kX4oH8V/N5rx0vtdP9K2SHQxPMyht++GzMBmvI6O2oneH1sa91b
            BjF7H4wKlfkF8BJ2BWEvXlZShu9aVySmO1d3XStkvO0hUz2fJQQJQ29tvbZkOWjS
            XgFGTAYpiyQwpcVZNb0MToVr9qUQoyc70e0cQZ/nJB9ND1W4p5KBSffzgfem4gAv
            VnmJFYvOvYmDCTeTsnemordBkU+Z456q1QVjB7ShZhVsAQvfCh5u3vtGShvUJBA=
            =TPKv
            -----END PGP MESSAGE-----
          fp: 7DC67A97634AC8391BCA8948D2DB2587BA3FD47C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
