kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: production-apps
stringData:
    APP_RELEASE: ENC[AES256_GCM,data:S+q1eZM=,iv:nCM19+S5IugfFxrkX1tGCuBJBrsq2dtABF16MkEh0RY=,tag:Klfs4NDfLzfDyp2jl+N4FA==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:T4hGBjjuLaI/8A==,iv:HGQwtZJbP8RPVWbDDLc/hf/iUxMpiapFjr1+FQ+/j/U=,tag:6yT+O5SM7kGQju2l/gISyw==,type:str]
    FLASK_DEBUG: ENC[AES256_GCM,data:mn1boRU=,iv:siS0MHzxfEYqjJfEYOElQWl+Q7DwbfVJ4Jm78Rxi+RU=,tag:zJmJT7ndDsh9F3+2nR7hdw==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:vBE=,iv:AqWAQzHeBIig63+bMFicTX0WhDRIj7ZEeVryoPuD+cs=,tag:URGO7LmjpKjPFtSvSmD4Lw==,type:int]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:3hI0Z2xwgA==,iv:2uQ0AO9ZOrLT79NjR8OcJ33i9tpWqiCIqptilYv2yoE=,tag:+6Xbd0OL6NiXqN30GHWDVw==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:f0W8hB4=,iv:f+QJRRqonX4Jfcdf6nHtlDC+IMxsn1wxUN5973wwEKM=,tag:gAhbhwxeVUT6blPkJ+E0CA==,type:str]
    FLASK_DEBUGGER_PORT: null
    MONGODB_URL: ENC[AES256_GCM,data:CtsbS18v3UxYp72Ui3YZfZyVYDE3aYA2qz0wUamqNIXdvqDVRk5Fzzl2RGN3u7MhX7BQuQ==,iv:JZtB2n9mYxtIxtVIujXAm3QaHSLGH/tmQiTFYs6wZnk=,tag:HmyVr/UlT2ASH6IlqPKahw==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:495vtF5OjRo=,iv:oT7eyuj9gXEv+Eb/hxgss5zPLJKsuR+YdwtnsKBMWGs=,tag:zdQN0czxkx8H1el81sVefw==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:GE1syA==,iv:adMkz40tEya4s8i34usmfcEpoxAMIDT4xyhiiqaVHLg=,tag:qz5Pialp7HP2/vYl2hsCsQ==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:6i2E7A==,iv:+9hxBDtQjc1s3SRRiWwQp95dK1eHXmjqcMJDlKFb8+4=,tag:DEOZPDirzNxVQSdpT3wO8A==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:7/Mifvg98Nu4+B8sOBhWBauJnbFUQPUPVcehBd+lnR/vZIzpUQpLvaNr620XlOFfIWoly9DkHEyaLz4hOvrq0hVPtg==,iv:dZeWRepL+iVQlNxEcVl/CbInr4YfywptNx7c+eFafSw=,tag:Bv96VGUwFCkmTOPVyX4iOw==,type:str]
    X_API: ENC[AES256_GCM,data:42xdyZOWvxyQ14ws6GH/hNGIYWuFoAGmrf3bZz7y7Vw2d/xTgYqgewFAF2h9bNj8jtmc1N+b6A3L0A==,iv:AJpbPTqrfgesg6HfNY/4mGfMMMwqIwfj4UHq9DZKTCw=,tag:56X39ueOCrFZoPDbIHPgDA==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:WAmQIP5Z3uCaHR3xbbxJP/qCSgOAtizH93pFXHjYOEdIwo/40rNxN0YocXhuVWhUzFuQ6QpULI1bDXDibRdKQg==,iv:UZ5o7GKYHdkf+IwDHSaMc2XoO/mkOeWWgyYvmNHSuow=,tag:SDzjhjILBLEJKSCuMCVZRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQnpRNXlpSm9VRDh3TWU0
            UjgyZ3hGd2pKdzk1UU1KdVFSMzhpdCtmRHlNCnpvaStOcXdKUmFNWUw4K2dzSy9F
            ZWtaMHlIOW9yWVVXRGtZSnVhME1IMkUKLS0tIExMbmFTaDY4U0taVk9QTURiL2xM
            OFNKQ3BmM3FyWlJvNVFoU0QzWWt5WWcK8wMyZIT2XjwIy6xFIOOfHIlxP/tFpMxj
            h3YJEunQ0q7gQQoydSeKdzSdE3o9kHKpr2Bz25hk7ZNUDgeRbwUIuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T17:09:27Z"
    mac: ENC[AES256_GCM,data:sPIjJSQrK+ypUaFQD7yQoOfKQ9ehmCRvzTa1yZjE39pxnPFVmlHCvThpz9l8kd6EqaQ9tJTm+RqcT5LHZ+2+uLPEYM69ujm3SK9AKML6JxeKh9CELpLns/zwUgk42BsWhYRZu+8V5l1X/+xgQJQRLzi8dBfu47nKAGQCa7e5Pmw=,iv:/rsGts1dZmYb6fyaSp/5P2HsP7WZvW3uCNgkg0AVR8U=,tag:uCtQFfqOH0ZB6uemGPo9Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
