kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: production-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:PSHApw==,iv:KvEvHRXEyPiWnF1iT0IPzxt/qsgpC7/ZKmxGGLHZs4o=,tag:co3Wkb/4w9Yvayydl45Isw==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:IOg=,iv:tr3sJOi/VoyNQUvxJDSTZYkUptXiIKIOkCiT8/ElLnE=,tag:up2aoj+2UF9iec2PNiU5Mg==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:nndj2Y6Umw==,iv:7lhL8JEyp1O874GKTfzww4JRlGOm00CCWcvV3upCSYM=,tag:zOBYD2EjsFs5pF1MWI43vg==,type:str]
    FLASK_DEBUG_PORT: ENC[AES256_GCM,data:Gj5pqg==,iv:kGhAiIqcgMXM6OjCSDth60PcOhjzuHv9FskHN5PqT8s=,tag:gIE0u/was6Jbw4iAIT7Alw==,type:str]
    MONGODB_URL: ENC[AES256_GCM,data:+sr/8+sdLlXgbFXA4b6u5VC55NmfYVLaaHlVLPE64h/oEbifqAhgS50KNB2672LuVL+qHw==,iv:83f3JM+qnWDL+Zv3zy2rSIIDTDKnw7o2lfhw2lik7Ck=,tag:FmT/ES+6q6vX2Kv/3o3/zg==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:hb7STbJaI0A=,iv:wtFC26rKXffROBQRGko3IG5Kfkqwjy5uXQSd+jFYTI0=,tag:Q27FemdOhXqGuhxGRts/Og==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:oDwctA==,iv:ho6yPBlajJT6Fw17YnfydIIHrbXjkRZQ7GgSX/+0tMM=,tag:qA2POhUKZYEQbhmEwdWHrg==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:DDeqYw==,iv:+bG7LBeNNQoSWWifEQh+jITvsju5ukptracvvwWWkkI=,tag:BznSoKPBxUs8UqB9yP3iyA==,type:str]
    X_API: ENC[AES256_GCM,data:/ph5BRBMgeWkC1TATPXSR/hd9kB0d2g7HeDFWQIl7dJ1fCO1pdMuIgNEIaTjVPB4hWXsCINX2fnD+Q==,iv:f0Ro7+KmmsnpyCaism3txiAMH5NL+iv2aoxg29Gxq8o=,tag:pyktiOA0PbvB9TDkC+k3eA==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:QwcO6Dx6TAtrPSUXi+EODW+OF5GK0aWcAJIov+OpHvRdrYLknKwPmEgqL8Q7Eixh41jesJauOr++YyWCx0jIHg==,iv:jLxHRYTLZC+VyWNAjz4yN0lUArQN40j9xHhoaMcHjho=,tag:EZcl3Z3qg3/UcmEfXVRlWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-09T18:52:03Z"
    mac: ENC[AES256_GCM,data:ZhVm5973CqO/oFTw2QKYDqrGRbMYKrc2d32uMHj8g0BrN7aWzni8Br5ag41APwlhufrxLrmCF/4mDLaURQNEYWgnCgejj1ka5cE/+6sNtbCHuVSYRfe0586fp9XBab/xaUhS5bCUFYYADdxIYJ6C6dmTOt1umLTdj2Y6TaIRNAk=,iv:hEX3gbPxN0t3TCaLUfyIMxli8vITxxffoSMFjjM8BQo=,tag:h6BwlvUP+VxuD/E6Vuu70w==,type:str]
    pgp:
        - created_at: "2023-02-09T18:52:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5M85JgDuXmlARAAh2j70WQEiIhuR1uFESOQHey15HA+DoqHKc2ymUXsaYin
            G+gmGey0q2LSXob+vwmWZVprukZRJDW8Oy+2MWr+UZdYUOmBqn7kp6nZJYit1J33
            d7277Je5o26CvxbhSib+x0bRGXUQEb3YE/K4xOkbAhQe5rW7yvlwQGgyghAvTjte
            LFC8gwo9EUQ9xQN/hnzJpnA+CCtHc8cDqJDAjjAk9xZvjkNoaTm17cKgJMdBlFz1
            UU/NPfJJF0YGG170COHKddGx44WnfDmfmRmoB9jcpItF2vYDrMm2Furetq1p3JZJ
            4KEMJNHQtd550mREFHGNfaPDqDPDOinuts/ujQb2tgBSr1O9sOrZMZy8+38JQEod
            m/WcLFwDRYnAoC2Q6ASyTMtnIv9g7oWJ4O42hi+oWjlivXwUNpulPlMf4PBmMjnS
            SwN5SzUZe+MHSSVLGMcmS+6vDTGCqyrJHyuztw+JgX21GPVDUN0r80jJXZBYZPap
            1OYnrlb5VxhpMDrLBQixwnCIwtA1u/K/nLnJD155LB90O8q171isvv+UNTXsCm2k
            SWyveByQ+ubIVy1OD3V2uW6z7jaB1XcF/hGGVTrYnQv9Q8wIPWfyZ/LARBsR13+L
            /ULYO77em/PPji2NNNciNxtmKLzEdEVKpTzLzkvJiFOzPapkXOJvLPxDpvv9d9bS
            XgHSpuqO2sEqgPnQC6twi4E6Ae8rkSFwN/v6qY0pzz7Y8FFtOyXLwZVvQ3XryROb
            fyYgzzxBIFnOJdd7cFL7Fz1ltK9acW6tV0y/GiWx4XJbVKCu5QBHS/yGrfrkQk8=
            =JYrk
            -----END PGP MESSAGE-----
          fp: 20C09F657E7065AA528BF929A7A5C6E00137AADD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
