kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: production-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:HB2E30s=,iv:O/mAS4vjCa4d7E+Kc25A0LteUINji//PC2zSD+FzUVA=,tag:EFQUgR38vMv4rEJbhAQfeA==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:Xn0=,iv:+QR8lBcFydEOyPE7Ec0vVVtMU8SHjWYNlCxfPTpxSUw=,tag:3EOou7PvrNVwNCZ45Qs0tQ==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:oUvpBIkX9w==,iv:NwUa38Z0p0kWozy3+1bVxSr3BNzPBRC/xCbRlLqqKiE=,tag:EsS6jerPtvyJbx9FqgoC6w==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:s8PvZeM=,iv:ZQsHWRwGZtN4nTv2WLyvBpPpdwD2AydhRJTJIyVJ+XM=,tag:u4ymyqRNh85QZAZznjPXuA==,type:str]
    FLASK_DEBUGGER_PORT: ""
    MONGODB_URL: ENC[AES256_GCM,data:of5Q9H50wY5UxClU8yaLbTDffJNxv6HJPDDW+W5VRi6zQE9fwWkU2LWxYc+WOIDJv7Cc9g==,iv:/Cnr1KN/UYPlzH8higLfyeDdIZNWwctwPlBVJgUNIUE=,tag:B0b7D3XQwtnEwywBw2lYaQ==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:FOOB1Z9rlQ0=,iv:6T14MZjDna508xOLL/bHRcZ/rdXNPIj+DYY0NUoGIWM=,tag:gHQdnvi+y5HR7tv2/b2JOQ==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:YO3GDQ==,iv:KCdh34DtFV6zFAw60sxU2jsXLbNarC5H1PAtah1xajk=,tag:uEBP9c1Ij24j558zZDvXxw==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:M1SjsQ==,iv:om3FWX7ewKEfgR8d+OEB3ZIhuqOFZtdL0OuadsGYppE=,tag:n5PSOuqZFYZvXXXK6dUNjQ==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:RzDOBQZPaq0DFpkFVzZgr+2XjqmCTzRCWX/YPoQg3X5pVExRPBA9huRRJVlQ1YyjOQdspZU+SAGc461kVFxyHus+4O01bLPHxtg=,iv:LAaNKAhi29FYbDxxUba7Xlcy14w9dZ+cs55MGl0dmVA=,tag:vPmY8gBsWenEUiwOoDOjNg==,type:str]
    X_API: ENC[AES256_GCM,data:iO5Tp9NH+2qrsZn1hI4fRwdCA23zXEZYydjwYAQdznnGBgpgb0Ljj7BHFmRqdipAeQzeXQj/+Y9jBw==,iv:qMfSvgVO+T6+f0xAq+uVwjT2p/18yzyCiItJB5/EEUo=,tag:FCDCAgowQgqygbFcwQlBTg==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:uCuw6mqJIuzpSMiwx98Q9SMLXgJHG81tv2jf9kSPL3DhefgfbV4SYCf7DELKSnDWja8smsIC8a5BXKs7OqdefA==,iv:dpBf2loTT4fPzMopQq7QUuD44jg93wmqaBhKMkBsw9Q=,tag:v12iVSSG1jLzrUyaUwK5ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-16T21:21:43Z"
    mac: ENC[AES256_GCM,data:Y6MZZoZKHDW2Zr8opfnjSpRCwjkdWJXmdW50MlqC8m6+neI+MCbQjApjEZPi0k3DRYgmmtXkaBVhRjfSn+hc41yYvJKmb0dTXy9ZvhFkG4o+28TlxZ3Bzkso+ib3RGK9PVD8yt+4lTEKpfNUolEn06MSV3ny36IjYxStUYIwjpk=,iv:LLo8gEFiVpsoIJEBpy558g1wH7KD+l0eaHwQoygIxkU=,tag:/kiXpREzlwQYzjt0mkjChw==,type:str]
    pgp:
        - created_at: "2023-02-16T21:21:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyeXsCGmRZX9ARAAmNba8kgR5Pjs1thp/11Lix0GcAk3na+649O+CAS94PkW
            krJdsZPIqCiEXU2LsmuOYYP0jmqmsyKNX4jWXk3QtY6BgvFY5srtCcIkd+7fi6rL
            w8VpCcHlFhhys974olUM06hQVUngGEh7/ryJYexOIKWXFSCc4CCdtVQB+zDj0WQn
            JU/5LCQpa3OMNZhc75A8MsHuIo1MoOjFieXnB+GwW5CSOG23XqMapqtFEzFUYf0K
            id84Qb9+i0r8/TOXMRKlVCgM8uzkhNg7L5ODjqExcrRtuMxvX6d0zHBXfcsEiHZh
            ixSyW1J6j9+aZOAr1UmI+aRiXQV7NGx7oZ9gIHNdyW891DDjLII/R2aQuXNojcXI
            e4fwpZkXqmxJVDPgmj/xBTTckr20Doeo6vmuQ7ODWyXEdW5hmcdI7PrBFVXHAvdN
            rjXPIJAwSvX0NCbpAKLOu5tyxEUZURiFnGR8iyCOqhNYq6m+P6+dMSfwEPxX8U04
            xf29B3cqH8MWA11U3/O9KrqzyE9XBZeKQ+Rf1WkPpgitfQPYkiyzIeDj5mbsyxV0
            GZf6jUND1VxmMtAy8z4Kq0uB5kz51+BE+tACbUIr4uICDmqG3NwG4FcdQIsqwmMP
            T1SGxHY7TrJ8IETKXvwuTNUlLCzz88yR/1rBstzWmd5j2n++skFQsAEm0DrGQwHS
            XgGyChXxM6/AieJSVEUiuZ31bG3cofL9uDUNKOQX+9PULjRGElyxWBS4jL8lPWnw
            BmzCdPSm5C+UpFgqV5GywkIaQRbJvqt2EPOvWo+rJqRwKkb1OYUfiQSgmK2IJYs=
            =uCgt
            -----END PGP MESSAGE-----
          fp: 7DC67A97634AC8391BCA8948D2DB2587BA3FD47C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
