kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: production-apps
stringData:
    APP_RELEASE: ENC[AES256_GCM,data:3bwko+E=,iv:zsfTnuoTR0fZuCQGHcz5CWGxGVc1cf6UbF2yPLt5dJ4=,tag:md1d3PeFhpTeH2+AIRDsCQ==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:t/2ZPWwWnNETsQ==,iv:u1mzDBC3obYDgF/A+KyDbrbS68L0/PdbpLNBtQWHyMc=,tag:AqookUmC7xHAiL5aM444WQ==,type:str]
    FLASK_DEBUG: ENC[AES256_GCM,data:GmmUM/k=,iv:Yy8cBq9jjHFVPIfvyHTKdDwDXkgo1CCqtuQ1xpTlr4s=,tag:klEPa/4XM0fdoPlPWE5pNQ==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:/XY=,iv:dN7ISgSeeR0nLV4ozDyhDhuAU1iy677lWy+DZHD/i9M=,tag:33x3j+V3w0Iqz8T8mX0ZBQ==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:37gNwrLE4Q==,iv:oHdPUzhsTrM76PHQhjW/B8KaYCWFKCjbnsBSZeVaEyk=,tag:avq1/eTcZ5XPpiSbQMLH7Q==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:y5BvZOI=,iv:5f+uqmlhxFlaUb5vXvTuyH/64U1LFfLecmsYLIGmvk4=,tag:A9wRhk4ph+ZhVkkTndr88A==,type:str]
    FLASK_DEBUGGER_PORT: ""
    MONGODB_URL: ENC[AES256_GCM,data:wXCJWchsjeQM5YLX5VyHUwG+R7tG1GbZStE5sG7NKoI6lNJKflbIJO81dn8gvfXVMWwIpA==,iv:2BmURPqKbj85h5rauerel9FEprlRJytgZ3c2uGpni4U=,tag:J/kK0jgEGNkrXdse5thOFw==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:tApctIJvSzQ=,iv:aGKFDMvlrTqE3acee3KYLuwL782XDau6+cUgSp2USW4=,tag:DJDBZMu4bLVeDc6rH4iWew==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:QdgWJA==,iv:q+Tu6DhHc8lsAj9d1yVICYuNF1cJ0IzMCR8GJKTfYHs=,tag:fsWeO9H0AWlH3BV6cPu5uQ==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:TLnJDA==,iv:0dQec8yxHMeiwWbB1JgrMLZ5zR24iYEcKWTUxg/5QJY=,tag:ZrEJHdj2yzAbL1LRqRnAfQ==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:sh1v2fsPMEEnvth96LxKsfYrecyY3Nj7fqFFXimr+I4HMllgnOspPFqTR3BhQ6WqNZRvzsxYnoyOlQDhc5hX3SOcNg==,iv:NqYviPg26jQJsLq5DD/hwjfAKwY+1WLgPZKbd33tQzc=,tag:B/LjCveF3rfJkqQpdEq6Wg==,type:str]
    X_API: ENC[AES256_GCM,data:zIcF9KZvwYDQRg/R7eoqJ7aJJz2tq9XvBcBff2Lh7C4wzNYtdIrl8+LwUdSLhpb/wGYrlII8ProQzw==,iv:hcysx5V5TNarNAYdAltMNaVhTwao7ARMXN2IWuEJNoA=,tag:MQDcuZOuAC3YJ+/CLuppqw==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:qJnTFK+e4VEMi/3MdATaZ4cTQh6J7QEcbCQb1uNAt9qkUfdZZE/BQJaiM0ijzeZ4vxRjBFPoZmt0f99mi9/L3A==,iv:lmigzE+ETUeFwLkLHxfR9PGhhNAB3O4aZh9jSi+biRM=,tag:WzLEjMc1/+jL/gn4KulVbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SGxva25KZVBBTGNhSDEw
            NmVmbElKeWtIQjQvOWhKc0xGTEw2NSs4WWlRCmVoSHRnbHI5eHNGSmxNTlBzWTdG
            akw0MHp5L0I3YU1EUzVZZW4rblNFZE0KLS0tIGRFR1pmL2JRT1ZKendyTjY3K0RY
            cTBPM1R5Y2U1TUZ4QXJIN09lVnlYQ2MKbYdiD+m+ZmO0489uBowyJIhhbrC0Lfpe
            F7UU4mbI8OST6NpNRmDlmyTIGI6zK5FPe6hMGPSubiV6HOGQ8w4X4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T17:39:42Z"
    mac: ENC[AES256_GCM,data:xQliztk/khodXApdLes98eVZpj45rwDjGUSAZjtlnNubrZ1cBH94qdspC7CyLuOSgQn85Wf2W+OahWgqRgOpLhRoLCls+7AEzscZX4dEtMQoLdvlkz3f/Jh5FDQcoQ2tQPL+zKz4nPgWmO34zSWXXViToJaLXsk7ofvv6nqMPpw=,iv:sZhVPU8sIfT24DuE0jpXUTcAOnNImiW9/SUhdeOzFcc=,tag:h5emSFcaxZp9I7WyK3JSOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
