apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-deployment
  namespace: staging-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: rempeloliveira/public:cart-api.v2
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: cart-api-secrets
