kind: Deployment
apiVersion: apps/v1
metadata:
  name: cart-api-deployment
  namespace: staging-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: docker.io/rempeloliveira/public:cart-api.v2
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: cart-api-secrets
