kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  name: cart-api-kustomization
  namespace: staging-apps
resources:
  - service.yml
  - deployment.yml
generators:
  - secrets-generator.yml
