kind: ksops
apiVersion: viaduct.ai/v1
metadata:
  name: ksops-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: cart-api-secrets
    envs:
      - secrets.yaml

