kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_ENV: ENC[AES256_GCM,data:VeqIzqNAHv+G93Y=,iv:lDh6LB8JEnY8tvDZ8stW/3tUcbo90XAFaY61sjo4hDg=,tag:msC0NeV2b68SiLjA4WeWsA==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:jU4FUA==,iv:OgtK8pNQUU6tCBuG50TeqIhZi1NKaEscInFwagrm93k=,tag:TXL3W2XNKVIxpkWLz5fmRQ==,type:str]
    FLASK_PORT: ENC[AES256_GCM,data:27Q=,iv:OHJcFzuaLLQogPpiIqg7mSg7btOGL/2AR+fVSe8yIsg=,tag:KCAV4eDbvfomurgHizlwCg==,type:str]
    FLASK_DEBUG_PORT: ENC[AES256_GCM,data:93yITw==,iv:gWsXO28vWBwiAqjonmYA3c00Vm5rwdCLwN21FP0m2Bs=,tag:oB9ewnUG31ntAoBmWZnrBw==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:YFMLiVplo/s=,iv:CErQ0m6uX3Xsi7AaVB4yGsHf9QO8+J2EP4OWUfaCRJw=,tag:I3m6O2oeXmSB4nB98xLnDw==,type:str]
    MONGODB_URL: ENC[AES256_GCM,data:wEWn7Mt8sdzbKip9wGdjrvcjbnoVe0QcX9WoeY+m4/VcjdyoJ9uIYGb8fKgb3Y2+Yo1ieg==,iv:mshBjPhmtTVJ8wY+sQS0cS6CTaXYxgAU/7P+xtuBqcw=,tag:oW1DTWNE34CxBudoV5VjFQ==,type:str]
    X_API: ENC[AES256_GCM,data:7SGhZwAVm2EiSsGMPnol7OenfA2HyN5KxdvMiuO+sF7/O5kd7ApcYJZ8pGdaiHkLSdtP/9A0BzTnmQ==,iv:5AdwGX5Qzu90IjZS6dhS0KgQ5fhbPEUUMGPRRwialDQ=,tag:dzaXvYMEYPHKHReTviaL4Q==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:uKLhrThFMJDQcL67sFnePXU9DGJKvKtECvXq350PYAtNQaU7EMokXskBvylnIu0H/2YwHvedqeikva2bzc5HSA==,iv:31ag4eluGY9JxC9BlnSAs1UbhPmcrl9NWjR6y+4DKl0=,tag:U5sk+t9pcpiuHUxbgG5E+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age147qu8j0d8zn2tz3u2mkl4p6vwsmhv8eqdvh6rcz998uaxgx4npqsyrd2wh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSUFRSzl1REpMM09mV2h6
            L2VZemxHK2svWWVzNjdnbDhYanQzbGdsK0JJCkZIczBMTlBTWkRLa2pvV3lKSWZL
            VjRTcEluc0Q3RlRsck1ZeHdXVmVjWmsKLS0tIExlVXJEekNKZ0paTzh5MTcxTFVx
            OWQ3blFMY2FOTENpZGhCSEloUlhQdGMKCn9LEVsu1bmO2l/2fQjb2faIG4IKueq7
            MPNf2HoR2qOiSGzGGRklQIgofW6y2dmQr2cszCgsx68gt4KYbBxjpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T02:24:24Z"
    mac: ENC[AES256_GCM,data:5eo8j/CjpPE1twK2DH2LLe2KP0Qs/I6trbgztNO5WolYfYw/21cS5y9f5MW+046HYnHjWjp+3DkMFsSdEq5qqzOeyHAf/GJmniv0FRDGdFXv19VzYZMSxoF3D8LaaoSNKcpRsc2JRyS+Ez5jb2/J+onJ5IfGlsWWl1HLgaEEccA=,iv:rEoNH1lGZs+t57Bi6oOTrYCUpQQ8tWql87V+/6F7+vw=,tag:v7pjyiYPBWIC8Ix9hOIDbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
