apiVersion: ENC[AES256_GCM,data:iKI=,iv:lpGTwtIVnzZmTa9E45WUOOcHm0lE8akPNyiQ8X8n1rA=,tag:0FyztYDQcy+gLvSNBLAHAw==,type:str]
data:
    token: ENC[AES256_GCM,data:JXpvvH/eFZANsjtsgX4plxCsdYCPPc6Gj85vJ4S/9hgMQCvGjpdNN5RtWJeqB2Fo,iv:GCrhxncFAd/5IdJTzEK2p6DPZ1K6YtPZrPmBjZIL/EQ=,tag:7aaaOK/VfYZwOzEyGVdBbg==,type:str]
kind: ENC[AES256_GCM,data:AAJO2Kx3,iv:ErtRhNJbfEgLraVJ2PMjoTLhelCv7sqYiodQcL9yhbA=,tag:R9wVQB1hZIDW7Bdr8kADBA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:jqIddLt/g4Dw9YDgQqpqew==,iv:iNVZYqRe0KOZ6CIuWAzpnjq+Hsj1cOgtuKFupjQlzcE=,tag:336q2K2qpwU9g7SBWRpc4w==,type:str]
    namespace: ENC[AES256_GCM,data:Lr6dIdsD7JrBdGDv,iv:qbQ8NjkAue+gmxP2Z8PH2ciailB5j+KHs6MnZZCSREA=,tag:8m02ZDcKz3WvyrCyf/0f2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-26T14:09:45Z"
    mac: ENC[AES256_GCM,data:R/8wl0VrkVIVLbRrm0+pKKlfKVhh6GM9r15t8SvhUDEXpakoXJYyyVF5zI3YTeP+rPV0SVvqzQRxXoYTXLHHHzGgTPAzWBdSjvIcQRF0fBG7O4/dwG/WJ0rqtOFoPeoHOOIhMH00UFFxwvxwP01O+0PnFoDI6M8l/C62P0O/y2w=,iv:vHqvBFJMRaFSOU+PVsfCeG7bFKrf/KUqUgYbYQWiJd8=,tag:Z7irzjTIQmldlTTjbiAtSg==,type:str]
    pgp:
        - created_at: "2023-01-26T14:09:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2PARcZOfjZ2AQ//QtC1Yc5eElhw1qeJ9q0sXZ2kZf5FgET5GvzHR9phgLIn
            Gz1EaZHw1EbK9TdhjN9ttfqerMJx6WhHZyWRDoY37h9UXvInVd2FLLnrfJ1fL9zV
            lNjT6hARo0sBr0pJFs9N5n/+DqEsFp5nEfNa+d+loT0V9smYhzOe+hR1h8/b/MAP
            /TsL6AturAe1NYCvXUzMjK63NsAhGiz1Wf9c77wXoQdOHZIaQeS5XW567sBw/Vwl
            vWpVoWytePvDRBhbO1/MKSur1iSu84fc2ZxBgJAtcCZHL7r0BKCKcoFQFPBMiyLI
            qYC/54WsWdBumOhmh7HLUVHJIgBYvy0T32dkZSdz25oAGMV4BaX/MUxzhl7h2LAU
            r2aa7Kmy3qI9PeoIvTq44W6ykj1+3GdyMYO9IDq06dI8+y2mGmD/xlujnHZSzhqE
            pD6kdZO6TvOYdOpgOAAeqLMybz938wWXVC487O5Rqw2D7UwZxMMgHEQp86hg/psq
            3c3158zL9WP/aogjl3OM26aJxPwlmm2+GjxDDlGYq7H66vTXfQGIOewDKqeHSqpT
            SdEGo6+Mmz6QZ6+kvCaXzsmxoI53xiBh2+dbslzPa4Q8wQmkJd8cVcQcEpinwnRN
            Nqv9hp4Jr9o+hpoB/jzymccvd80fl+hYLrmrBfJmWFZxHamxi+WgWXGRpCitWD3S
            XAGT6OAYftAdLISyH79kjzxiSrtv4AXCua2mSDU1rkOgcbViCgKTAEkVX7GR5ykH
            cV0KbDJJjH0oLl2C+m5gFOl3CKeAgv14NDqpSF5Pvq15hFk3DlA3BXfCcoA8
            =ickR
            -----END PGP MESSAGE-----
          fp: 674EC0E4229EA1C6821B3567F9CDA5F1C9F605CB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
