apiVersion: v1
data:
    token: ENC[AES256_GCM,data:bTAEmmYfYeZ9EKbj6N52lfdyycMZUjFPC5jO5nrzZ/biaXY/paZ7QPKgsGs+FfXy,iv:UF5jRq3TqHzeiplhYs1DxiNG8AVDkqS+E4c+3cXKBMI=,tag:iv/zk4UPIO0Kb4y6W67QLg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cart-api-secrets
    namespace: staging-apps
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-26T13:20:48Z"
    mac: ENC[AES256_GCM,data:C7leDPb3bvnW0L/yXiXrmnoLuu2c6jihQQaQcUf9ZIin2V1Uhb5hi6+osCKM812cIvy7Et44GgrANrB6sfcZPo1SJ8W2iOSh9N1xy0SCTSBz4MLChBz4GVFscpUaRyQLZC1L+yH2u0l6F5rSkhTrgh4Evn4gB7UTCx+2+4raVeo=,iv:PJfRXxz7BibYN8vJMS0AGvXmLBCM3BCNX6Jv3HHJm9E=,tag:qdRFMO9bbOmKW8PCvzsRyQ==,type:str]
    pgp:
        - created_at: "2023-01-26T13:20:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA20mMOh61RmGAQ/6Al3/b8o7OakmVbvk/nE7NWsyhodQz3ASThdbAyIUS10u
            3GZjR21gwSDtyWi0krlLYuk7FKx0PlHqZ5EpGIrU9lrZ0RCMaBTfBtYup0o9enxE
            WzsNjkynsgXk79mMRzAzciJgnSZzGl2jqEN6n2KlRP5/+QGyRfDxFPA8a1+lUrd9
            ecyv8HaYaLXkCYHaqGIUwIBMeAhM//Wp/eGCZl/sB0KVhlC001rL4/ZZmAQ21KLx
            Hdr6Iw0/J79JbMTnlhsTlKeN0Irzn7RXIHuganRB+zwWCk6Gc/X3E2gI4wPpw8tQ
            yoyLKWNqh+myQfnyLaTkJkuLG31s7NC0f9+VIShKLmxd1vIrAmiGvg7hPdjim2xO
            skyauD6ART8GDKR7BSpEJhLSGih5cIsdn7xk4VV/8ekmBe+r+x/ImqdJZCQWWX2m
            AlGcJJjaV0bwh7CHeuS1s9uzysEddWVHAJFcDOpkoFT7nGMWp2X/Dw34dKyzWLcT
            309T61+1ANiBBxy79sNe9TQY9Y66+C+A9h2CxolSJq+jHH9I7ztgLr78DPxEjJ26
            0cwqkYj3eVkAE2I+ZBLxRpE7n1Iegv9/gybXxlxBUzTwsbQJyR25XQYapTUcRfIb
            /uMeCVkPaRgIC5r5koqM8lolWKB7Ir99fYij3vv+In8axEbmmr98ANhxfXK0vMTS
            XAHeslNv54akU000pNlS0rCPD8YMJBj1FLQHiVlyNX7sbUsigjS5Hda/kciZa1lI
            UlAfyXWsXbV6Ck/YA4TuPXqsF2CtBl8x64ywkxl/dNHXI74kZB9ykLeTeps8
            =2WzE
            -----END PGP MESSAGE-----
          fp: 9CD1E9EC625E404CFF0A9B47D10578E9FEDCA8A6
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
