apiVersion: v1
kind: Secret
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_ENV: development
    FLASK_DEBUGGER: "true"
    FLASK_PORT: "80"
    FLASK_DEBUG_PORT: "5001"
    MONGODB_NAME: cart_api
    MONGODB_URL: mongodb://mongodb:mongodb@host.docker.internal:32002
    X_API: https://3e50cd27-cf70-4c8b-89fd-869ec742555b.mock.pstmn.io
    X_API_KEY: PMAK-6137dfa173453700461a33da-8ecae3393710f0ceaff58d84c120d7cb90
