apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
  namespace: staging-apps
spec:
  selector:
    app: cart-api
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
