kind: Service
apiVersion: v1
metadata:
  name: cart-api-service
  namespace: staging-apps
spec:
  selector:
    app: cart-api
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 80
