apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
  namespace: staging-apps
spec:
  selector:
    app: cart-api
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
  namespace: staging-apps
spec:
  selector:
    app: cart-api
  type: NodePort
  ports:
    - name: http-mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
