kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:pBwUgH0=,iv:/aBg6AeEUOkppd4HtP8DLihZ7C+I8i0xp19oB+ORImo=,tag:0lcaxOtFqsU0meI76AdHdQ==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:fHE=,iv:fQl6OHiAjX1k0Kdx8rXKb00RHaFhzxtchlzP6W5iDcQ=,tag:n3ZpyKVv1MoByHzw7Y78rA==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:akbsYUbABw==,iv:UJ9MKapsQadDv5nzn0WQIrThyQYMwR2A61+4BJ9PUKA=,tag:xYHevLaenBOftPmaUexZnQ==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:X3XBGv0=,iv:LINKWy7JSMfERTwNouT6+QIlIkZNeW5sZ4iNWF2PSbg=,tag:W4m+/NxS0zTOeb4hsa9v3g==,type:str]
    FLASK_DEBUGGER_PORT: ""
    MONGODB_URL: ENC[AES256_GCM,data:OqqcG0Ag20FEyi7Jy+WPKWCdxnrNXx5fv77mGzBzta4txv+w+RmzChW4ahgWKOwmcT4CSg==,iv:E87Khb8Gl5779g9Yajmb4xQ73F6UAN4WRLsf8+aUzCo=,tag:fPqfn9A9wRA0DGG+YDeWBg==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:A4boEj1I3dM=,iv:HrEbu8qfo/ch3Lp3vcMmsjeaHjUDu1R+GChDMCQUzPk=,tag:k1p4R2YIimGg2x+3MP4KLg==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:LhiYvg==,iv:HEs3GMHuovRaXJdpfEj48vv8WGUd4wlFRELm0iBMbJg=,tag:IVwc9ivdf8NwaJj6AeHg0Q==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:i5yn8g==,iv:7S0Wzhz+4U+JGR5SioC4uvi3fiPssShGhi5BM4u7s4Q=,tag:RVI+9hw7Fd4eAjWkTvDpgQ==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:hPpGlyv4gn4qxPteVTFdPfG26dhDfPipRVNRMFBGRL/KlkqTZ2dppGsYKiZM3G3riT8PmDB7S7dLFlzHHIYw9OUm6soBi7K66a4=,iv:qmC3cWArDFJoTRUCNdgfy/h3I/DGnXZofRIwMBmaD5U=,tag:EYG6bOCWVeZJXmPAcrt2/w==,type:str]
    X_API: ENC[AES256_GCM,data:EfKMhokLGNzaMVznEsPgCDYcNjV/RaAt7r3FkxG8hCpy+/xlw0nOzZOTiQSJeb/liSuRO08qPgETmg==,iv:9aVjNHIvOTFEYHeaWi5iv1ScX06RHRgBqnxexQtemp0=,tag:fOijGtM9Hc1XBGQQoys/gQ==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:WBvfcVpdH+ELVMrtYmJ6ScBWU53OCikMGEcnVKgHvXmbNDtIutAvFSxLAkwSrcYgKnnJL4/U9VdKRYP/i8qYeQ==,iv:kXd2iQ4xXknal8NFkJEPHIExWZmEEeoHZAppWIWLsY8=,tag:ujjhx4okkYRI5B8dJlK/Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SGpJekVmMm1DK0pFK1Ra
            d3RVVmZNUVRoRTJMdmNjOVNHdDNUdTA0WWcwCjIxS1A0NUQwcEVha0xXMHpPTGNh
            MkZjMjgxRUk0SnllcXdrVTFPZ1N0UXMKLS0tIHBxL3c5dXA4Tm0yZFA4ejRVUzMv
            d2hpQmtIR0pzdTJncmxNYWdkSzFLMGMKvZVUujS7VsigKcBgzZIyDtbmsJSN0FuR
            GMvnuHaqUA8i2rfm6qToaLUWhLJNSEpUTH2H14bTKssUKQ8bD0z0kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-17T18:11:23Z"
    mac: ENC[AES256_GCM,data:tz0vi3entTzw5beSY7x+02t6W1ryVZSDFtm6dJLkTYWmVjyI9H6iyjsoLNZF5bYH77DNapQM+LNZgnhgFGr2fVidv7IwXCtl23UWRBr9sKqRNKWmvwjpJbLBkQgFrKyxL5h3fznSW9DWnyHfQzbYU1IYgAiMXbemdfalQkvhvww=,iv:mTpjeB4AIbd+c8uzhRr5NhK2BaAwg0cIkqGP+hP3ma0=,tag:LSLPgpOdBBW1OEtV1OZNdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
