kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:rK7+IQ==,iv:F/zSyhY8kWmYu617Q/n5J5Gj6gU+TnlYQ2I8SJ1HLA8=,tag:DPM1mNnJwRYn2Ws7jxHl1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-30T20:56:33Z"
    mac: ENC[AES256_GCM,data:0JGZNiHjljbcIVWDtMX9U8HlloLu2FLhJP+ffwMVPBAgc+rE4wfQwW70yTEOMLq9YukxMx/Go5BtkLdPAKMPNZEFHFZPnqEiNNPXJUWYe2ZZciDJqhB13jGOJa5x3B4FIIeE0mVIb0oHtlTROrneXt+pJr61tiyvVgQFINcdRpE=,iv:2UixxaYHJrAyfZ+mQKNXDbj21dClLGJ3+3VrVlE4E20=,tag:obf1ZD0ACO3jyXYpOa0Xcw==,type:str]
    pgp:
        - created_at: "2023-01-30T20:56:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxR1xrdYeN0bAQ//ThvQ2QTEx3V/oIAk4YqK0xh5OQVXnBIbiiJ0p6SOfvIn
            V6aTrZ8UNYsb18X/5B6CsJ64pQtG1necrGmocAUIQrcTP/0folCewJWokco3Kz5a
            AvUyBeVIWSfZz3I673Qjbtl52AAYRLAulOAwTP6itBuv4Kdyu0oeHq8oDXgEyzqw
            tYTTuB+PQodWaWwmjjCCwdyIQkPrihlzj5808xYz4obFZTTHsKEN/ImJhMyevUvt
            ZaQ+D6R9fMLXnDuxaP3GklmeWYMuhyBIl0IcDZNzmOKoqixOW8D8JTps8LfH13/V
            4VLc2VaZANboEo3Upzt70HoTP5PGFn0XBKrKX/evwOM+3nu1+qRhP5kAASpCgTXG
            I3lEOB9A801sN2zkoMDgxPEYjrgMN7KRNq0AUDhptknge8SvlhpxVWktvBI4makz
            G/e3ZIAGrwloXrgB/gokDnx63K8mNdMOOJVYgxyMj1Q4EJ61KN+PIqQMGbUTP8cp
            eS16lYUMQY9qcGRa6F+6RWWmnppuDATwyQ2rRT7a2cmNkayq1wIX5cjY5UgY69L9
            V7swJvWjAoZIcwp9xp6d0IP+0wISCMIJefpfQJ2Nt3TdVtD928nM0PfDs+TENbUN
            kjDFV+og5aTcRU8mKoNqRbWHjIMHlDox1Aw44WTfHqjZQKjrFNzKZwenbw2Si3DS
            XgFcX+brSrKrlmlt6WiE1KWFkIN15NowaMQpcNq5VIAxGmLyKdXwvDNduUpI5KY3
            9PzpojwmDnh11t0CnxfxlWObxMO1BcHgva18GcmP2N7F4K4TRjRlggU4oVXocMc=
            =BSBq
            -----END PGP MESSAGE-----
          fp: 3FBC46A1DF2A1F09DE465037C2D92276CCB97193
    encrypted_regex: ^(FLASK_DEBUG)$
    version: 3.7.3
