kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:Ig1OhQ==,iv:u5Dcf5RK8HjH3QOQ0xnhR7oFkxKCNVli/k6vDw86SVk=,tag:sRg9+zoyUK3YwL0+4A9UdA==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:4bE=,iv:CBZy4jimCbU2o7g/v0HiKycfgc6PG/aN0gpFYEdc5N4=,tag:2zQMfvfqUJLRRftZ4XbILg==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:GIVeEoPh6A==,iv:MPTCpMn6tkDwKPa32dJxNPe0v1kbmOEb1fY5JuPlhLk=,tag:3VNZQ6suioYdquG4bhy5jQ==,type:str]
    FLASK_DEBUG_PORT: ENC[AES256_GCM,data:gQKChw==,iv:rDhukM39HIFO71ZwW4/VcAMiW7l/qzP379qh5JnG7ro=,tag:9C2n91SQO5ymUmwg/gVLLQ==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:/zD0xqD1AWw=,iv:45A5cqZXwA4JsQr54+3WsJl9KPardGiuXjUfL6qT7gI=,tag:cMGILEQksI/gKHO6yh+5MQ==,type:str]
    MONGODB_URL: ENC[AES256_GCM,data:75GnQgf3jXHmOOx9QT21ti1B/JmEkOgd9pzsyeNSMkm0CJYHxdBSx1pekt+3ACdYUjRfXg==,iv:b2/J/4/ZALK0Ciy8o+Z5DIks+iRyBUdKx8DR0coisrA=,tag:PRPf1YvhPnIhniVKlNNzNA==,type:str]
    X_API: ENC[AES256_GCM,data:4JHVwDAn630GRxs9HZdYtmYu16jO6Co/wP8Nh+wufkIw7intVBDenrKhzn1nv86fL1JbtEpIpqfLZg==,iv:betAuFwkttJF9VF97QZr66OsvirP2eHeksABCdZwJ3M=,tag:7mlI9LxMnjymQ/M/GALiDw==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:gA83uWsoe/l5L3/29dXWLSiA0LhrO8zb5lnBhwr4dIxJHid2Yu5Hh9c7ZxxvhQns8paYamnMOXMenfMiyaDlng==,iv:r4sjNHhixmWp+pxGKDoG1TlL7YvoQi7rEHG6GoZMVp0=,tag:THIgHwtmmjsjhhBu/uH+ZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zglv40p93pp63y3hsfhtcl3pgwm83vqkpdk3x5mvtnw7e9mdwgssfyag9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN1NZMWo5YUY2NGJvTGxm
            RXRIM2l1NUdZR2ZUemh1OUhwVGVPVGJlbTB3CkR4dHBDTUxVSW5YTFBnek9KNnEr
            T1J3Y2M1N1ozVEpUNXhscEZWQnhWdkUKLS0tIHhXbDJtakloUUhiOU9RMkZESk42
            bFdWSWlOdS9KZkZuSkVlY1VzQUw3MUEKDwSczjcNgaMyogdKRb7f4Z4nfQqh5x6J
            rv1aQEHHEAhqbGwbLBoe33V6/BQZov0NUA3bIoQJPdmaa4bINE6Fsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T19:46:41Z"
    mac: ENC[AES256_GCM,data:GWy6ZgrxY1vqGMTB5HOZ5OqwRQZ2e4lC7oh57l+sN8zzgGb1rc7ELvK8BONhwM1nZXKbqZVlaj1lNkME/nAb94l0/0Jn2Q42iz+VTmLMRkGN8XqyjycM63TCZszEqvdvPe9A2DD+rWnEP7fqaCi7d8/NQlymZqFD4UvLDrGMiAE=,iv:0tP5QAdz5LwqsWuMva96qgYdEtWyINBSMz3ZtsCf21g=,tag:/ilLCrO4XUlq5b4Q0Xu9kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
