kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:t29csQ==,iv:gErhvlrIIts8v5v7PR0iQlni/x5rYduYL4hySaIiKWs=,tag:t25mjTegUuAslkuZUC1Zjw==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:z6U=,iv:gQK7XP7pD+FWgz3vK/he2WfS/ZH2RPN+0HiH3T6nZ2k=,tag:GFvDvtfWpriOLS5dmJRl7A==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:+dhyWTCF5Q==,iv:hd63kQxHoDowo78w5wYKMEOg5nxqqUk67293A18t77k=,tag:gT5tre1sQaOIkUomW3/SiQ==,type:str]
    FLASK_DEBUG_PORT: ENC[AES256_GCM,data:ZIbrlQ==,iv:yEDqfwshWP+3IJfat30oufBvhuakT8M8cFwS4DGdo64=,tag:6jckC/BDUlVGsLyD/pvSMg==,type:str]
    MONGODB_URL: ENC[AES256_GCM,data:llqo+3MyVmZjyipG2j8hOf+4Y2Q4DKPIaAJ0vJmOFNgZv/DmeVuR5t4SpxQctL5NIeoIIQ==,iv:1+JitV8e2wdvkiZf61ofjYjHwqrZqhaWdcFWTKS+5/8=,tag:3OZeka7TFFtNzKNfQIgQlQ==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:9LfjPnn1SNo=,iv:kEsGQzXKYY2ph7WKs/0otJiemtcaQj60ArLrGn1zfes=,tag:HeJ3KXw8vgL//24otI8Zfw==,type:str]
    X_API: ENC[AES256_GCM,data:OFr1gsibfeq0NmH54dyhREEdAF4fEW9XUzzp+5oBSle3XYHQTOa2caQ1mUTfFLQR0KLdfGhNznkDlw==,iv:yPPeNR6K70cKyeONJuQ7zEjY+AOpZvewhn8hQGW080w=,tag:p6dMivDgd3QkfgwS56izVA==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:qnRGPvp8BKygU57VJ7uUN37bSCHf2ra6MWcqXpMRhB4fDLP4AiWeLm5V/ml6LKSLN8smDIu3k9oZgROyUsNySA==,iv:WWkrJMzISzb+yue6uuJKfn6BpHOV4MmgK02vHoJVvr4=,tag:FCkkAvmb9mSDmZOxXapsqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-08T15:16:56Z"
    mac: ENC[AES256_GCM,data:JyVMhzae4ToY696ygA7Dj3D/ohJFWkR1BMF8IXUFWNA4GeYchHKIP7MfysuXNlkhWRL9ac5+l2X1sbV3Say5VDggF1CCaZg2Tv2hNjxykPK+h5VkdtklgNsAglqtHknRh+6PqBAEvyVeihN2/fC44Z2WbMj19djBsrjfRTIEDwo=,iv:S2VsibxwlkPkAp0BitA2B8X03Ed+x3LqPtvf/V5EMBs=,tag:gd0p/yrJ4eiNfzKO6tmAzw==,type:str]
    pgp:
        - created_at: "2023-02-08T15:16:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5M85JgDuXmlAQ//SAWtoqkLXtyf5tqSox2nB69SJVWA6waL9f5jhlE2raXR
            eJtamMveqSqGfiz7nRGoFLiUba0xLsxf02IY2J4/b9d6u8xvj0TQ6KSXqabx4iVu
            0ggoZl1uGlmWGD5C3JZudnqC1Ic0ZxyoFyIPcDd4IvgFAfOOtp38cptb/oPkuuyC
            soilQyEqmPaFGFcxR8YCy8Z1na45TL7sysU2yMy+/LvXLFMF+DdRquxbVeNvu8B1
            ENATGpYq7o7fhfMzJGvo82MGpSQrCYI/tR6X3zxhqzSdPIhNmNUtJGkSQK2YQyRr
            9YBNhw7KvXOf9g7TZnz+KB15CXrDMURLHRjFKkvGFsDu6ZKxER02MLdFAcBvYhVR
            eqdqw5tMpbkvYgxNMjWGCZPhnGm1Z5/jJwYoM5g7oU0lOsClPAEaxj3jEruyCLdV
            pKEuSC2vxPp5wSUayPCriaZ4/6wZz9AOFyhEMEvqU6hC6zezIrhenB2AyDXo8Hsl
            jQPhQP44jkE5tX7jaYh+4gQ8sErjNf06rg+GE963fGkgvdYXuB7NA0Mp9JuG4Px5
            089bJMyBN6INkZSy1thgXNb3z+TOvoLaRNnTPQmOQbI3GtvksQ/Etsv0ra+hzEew
            Vh9XUfY0SGC+IU+333bWRnB2gftOYxLaFs8eEk9KCJ5AAimtE8Wgq4HRZdD+DBrS
            XgFic6WFzBg7bGfUvYP/zkp3KemSeERiwomxWhdF5X1ew7ZgSkkqDKSMjevuaNs3
            aKZeM8I5hLzN4jdEqieidyuId43cFrAnldTyHwzX/yITiZjCcs+sDei0NTegE5E=
            =sHo3
            -----END PGP MESSAGE-----
          fp: 20C09F657E7065AA528BF929A7A5C6E00137AADD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
