kind: Secret
apiVersion: v1
metadata:
    name: cart-api-secrets
    namespace: staging-apps
stringData:
    FLASK_DEBUG: ENC[AES256_GCM,data:7cnm1A==,iv:vWbB3ESbs5KhhYZLQMBG9/GMqbPvHmLgyyCPSHMJk1E=,tag:z7lcY5B07fjnPMvCIqvdwg==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:gEw=,iv:+pC5shTfYxnIa7oBdhWX7pznlWWSNoUcAvpXxd64nsg=,tag:Az4irN9RG+atqxOkizYq8Q==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:eZwB6o59EQ==,iv:neYekR8Tst3oKd5grLZ2if34OQaD/nM32RKvOrCbjHw=,tag:2N0jO6NqDtTzWAfcFeLx3g==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:l3kejV8=,iv:3kCeh/0xFrONu6rt4qcs6i5feGu53gM/qM/ytDmUyjo=,tag:CPHdmrA40b3HMnz8/o3aTA==,type:str]
    FLASK_DEBUGGER_PORT: ""
    MONGODB_URL: ENC[AES256_GCM,data:e85x716AIFQGPWsh1f9qdTDrmsEq53V2jOqv9K0b+DOPQ3AZf5uKx7Ae9I2aTJIzgz6sPg==,iv:lib4a7MF9DRenHj/xgYrPaDMsTre38RgzClpuLeZE1c=,tag:Js+p77GGBz/vKILL3W2sjw==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:CsIIccSGJKg=,iv:5DYkaAa8uCTHw8aoKROJHo6+/wUzXcNgWKBfBBUnTI4=,tag:VOZv1bJdnAWR1qhV9QFWKA==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:FLJDng==,iv:xnvEDlwGYa0742AEE79wiIK3QzkvZUuQvzdTwG8DWdE=,tag:R25AX+rQaslKvObi6LTH7w==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:wwexZQ==,iv:hWMeFoyq4+tFy7AT2qgOXhnXsFSgeV+Bw3lyHnvKTJE=,tag:o4p8r0euAYRNhDg1adEOhg==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:NO8IaAWlVne5oxJ7yNnN2lzEujRbRsN+hFSRz7wEYg+JfbgLmhOC9Zlrv87z3vMM5zBnEb3U/737gKehUA/P5fGcOrFRMEDzzQ==,iv:lYeD68T+W3Wb8IhKxKf2BTlC7gJa/0V2wu0mSnNH9tg=,tag:6fjKLhBvKE4w+zaThU/M8Q==,type:str]
    X_API: ENC[AES256_GCM,data:maCUCJ0mmt7CND+XQ/ODbgewKUdDEkHqcrH5AK55XDvpsc9h4dplVkjdaL0RPNK8stz0wVmDcFBdkw==,iv:bcXol2rYs2zFKoozmWz61xkgmEG2yDLG5V0SjtFOhSA=,tag:UegusAX1jmqpRk0XsGBpnw==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:C9e06QC2PDWdMKQ450GpkA2ppBxhU8O3/R9FwUWdDSfEvwNhgZY1yfQlZWA44K9F39VmOaC/M4cqbb5xLQEBew==,iv:s9uMtHvrqh08EWmCk0M8Crf9NzvSfTKcqXIF6QWXuNk=,tag:AVLddhF+LeBbP1i4M3d6XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-16T21:06:38Z"
    mac: ENC[AES256_GCM,data:aXbVK9jOk2d+cPrMTPfoykI754fh44CgMhpBZTSHPY4bMSJV90N9XB7o9HXddv3e0HKN8+A9rKFSUH1Q/LQqNJ5zXIL85A7VvLttA+amAXou/7ifo0mZHRjgaak2JStHtB9Tzg5Y3pIertwCzrnmDdi2RcRjGjxb1CYs1SRLMPI=,iv:8Yh9+cWEy4ZsqopK9e2155uLDM9RpZE4brYxVde1t+U=,tag:/uf3X187itK4HLVuWGknmA==,type:str]
    pgp:
        - created_at: "2023-02-16T21:06:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyeXsCGmRZX9AQ//QiGWiEf9XgOz7T6Mgxqz2Vah9XYt8fiqilvD/UxSjT1x
            qpe852TcSmhmOFG3fnWbubIUKijniL3l/IFAk/SiOkOy33FyY8vkE/bfCTO2w9Hq
            hLZDdbsj80xcLIQyq6kdpT+jha50mx809RrN0x5nLf500r8+u3lnUHj4WvkiuPnN
            yK33b0/XVFImD1k8fIAUNfGJklfYE2LdFAafrbrWNt083fxL0RHuQQ9tdwO5DbUF
            TJFc0EmPGteS9Et5QfpfUjOfTcdURVv+KWzJFSbYLiHzi6WlKDyHrM2tpx9tYtQk
            KX6EQQ5nuuySmzebIPq3c8lvdlY4X7HroBL3sod+fiHmb98SYZjWtAUvMsHvUGVa
            X0/QgX7xu2HlSNy8WoMIfV6JjvWWE9uwxcwvedXCPdJsHleFHzD10DzFNzfg4isH
            MRmsS6FpwzDpHABpv+1kt2M4euAfM0G4sRaxy/xvevRg9QJF1g+G/ULRNRd6WLBv
            xC8rO9+T1GYvjuMzpD4BQTi9Y3o0y6g4SpVFTrJ8wD7JXJvQj+XjbcL+E7Kyz37e
            BdGGHBz0TTOLS0N8MzW26uNkuLT6uqBwmlYQHI0RXUt+d6a9s2jyNWB1qw2mp7QT
            RL6EuH0DDnHqbeNYp3qAlCBEuyCNNFsqJ1as7oZQ2sjYT+fUx8a5EQTPzgm32THS
            XAFrTLV1yVywM8zwWB4rf8IEMcInkkr5fIYrCgVFbaWL3VdLEgQL9dK9sOft45yw
            aRLPWorBjiR9S83RL/mF1Urm6ce+2n5js3GjYyM6pzTczjG1rRvyM13oR5Yz
            =UgnE
            -----END PGP MESSAGE-----
          fp: 7DC67A97634AC8391BCA8948D2DB2587BA3FD47C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
