kind: Service
apiVersion: v1
metadata:
  name: cart-api-service
  namespace: production-apps
spec:
  selector:
    app: cart-api
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 80
