name: CartApi - on-push-tags  ## To run, create a tag using one of the patterns below.

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]"
      - "[0-9]+.[0-9]+.[0-9]-staging"

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Environment
        run: |
          if [[ ${{ github.ref_name }} == *-staging ]]; then
            export ENVIRONMENT=staging
          else
            export ENVIRONMENT=production
          fi

          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "==== Deploy to $ENVIRONMENT"

      - name: Replace Deployment Image Version
        run: |
          yq -i '.spec.template.spec.containers[0].image |=
            sub("cart-api.*", "cart-api.${{ github.ref_name }}")' .k8s/${{ env.ENVIRONMENT }}/deployment.yml

          git config user.name RempelOliveira
          git config user.email rempel.oliveira@gmail.com

          git checkout -b ${{ github.event.base_ref }}
          git add .

          if [[ $(git status --porcelain | wc -l) == 1 ]]; then
            git commit -m "Replaced Deployment Image Version to ${{ github.ref_name }}"
            git push origin :refs/tags/${{ github.ref_name }}
          else
            echo "==== No changes to commit"
          fi
