name: CartApi - on-push-tags  ## To run, create a tag using one of the patterns below.

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]"
      - "[0-9]+.[0-9]+.[0-9]-staging"

jobs:
  reusable-workflows:
    uses: Artbsides/ArgoCD.Deployment/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
     app-name: cart-api
