name: CartApi - on-push-tags  ## To run, create a tag using one of the patterns below.

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]"
      - "[0-9]+.[0-9]+.[0-9]-staging"

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo snap install yq

      - name: Replace Deployment Image Version
        env:
          ENVIRONMENT: "${{ endsWith(github.ref_name, "-staging") && 'staging' || 'production' }}"
        run: |
          yq -i '.spec.template.spec.containers[0].image |=
            sub("cart-api.*", "cart-api.${{ github.ref_name }}")' .k8s/$ENVIRONMENT/deployment.yml

          git config user.name RempelOliveira
          git config user.email rempel.oliveira@gmail.com

          git add .k8s/$ENVIRONMENT/deployment.yml

          git commit -m "Replaced Deployment Image Version to ${{ github.ref_name }}"
          git push origin HEAD:${{ github.event.base_ref }}
