name: CartApi - on-push-tags  ## To run, create a tag using one of the patterns below.

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]-staging"

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build and Push Docker image
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: .
      #    push: true
      #    cache-from: type=gha
      #    cache-to: type=gha,mode=max
      #    tags: rempeloliveira/public:cart-api.${{ github.ref_name }}

      - name: Install Dependencies
        run: |
          sudo snap install yq

      - name: Replace Deployment Image Version
        run: |
          yq -i '.spec.template.spec.containers[0].image |=
            sub("cart-api.*", "cart-api.${{ github.ref_name }}")' .k8s/staging/deployment.yml

          git config user.name RempelOliveira
          git config user.email rempel.oliveira@gmail.com

          git add .k8s/staging/deployment.yml

          git commit -m "Replaced Deployment Image Version to ${{ github.ref_name }}"
          git push origin HEAD:${{ github.event.base_ref }}
